'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RecruitOCR.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_009_12fce() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_009_12fce", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_010_chen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_010_chen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_017_huang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_017_huang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_102_texas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_102_texas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_103_angel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_103_angel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_107_liskam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_107_liskam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_108_silent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_108_silent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_109_fmout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_109_fmout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_112_siege() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_112_siege", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_115_headbr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_115_headbr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_117_myrrh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_117_myrrh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_118_yuki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_118_yuki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_120_hibisc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_120_hibisc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_121_lava() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_121_lava", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_122_beagle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_122_beagle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_123_fang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_123_fang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_124_kroos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_124_kroos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_126_shotst() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_126_shotst", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_127_estell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_127_estell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_128_plosis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_128_plosis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_129_bluep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_129_bluep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_130_doberm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_130_doberm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_133_mm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_133_mm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_134_ifrit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_134_ifrit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_136_hsguma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_136_hsguma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_137_brownb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_137_brownb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_141_nights() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_141_nights", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_143_ghost() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_143_ghost", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_144_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_144_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_145_prove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_145_prove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_147_shining() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_147_shining", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_148_nearl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_148_nearl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_149_scave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_149_scave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_150_snakek() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_150_snakek", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_151_myrtle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_151_myrtle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_155_tiger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_155_tiger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_158_milu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_158_milu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_163_hpsts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_163_hpsts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_164_nightm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_164_nightm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_171_bldsk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_171_bldsk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_172_svrash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_172_svrash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_173_slchan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_173_slchan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_174_slbell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_174_slbell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_179_cgbird() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_179_cgbird", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_181_flower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_181_flower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_183_skgoat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_183_skgoat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_185_frncat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_185_frncat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_188_helage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_188_helage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_190_clour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_190_clour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_192_falco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_192_falco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_193_frostl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_193_frostl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_195_glassb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_195_glassb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_196_sunbr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_196_sunbr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_197_poca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_197_poca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_199_yak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_199_yak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_201_moeshd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_201_moeshd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_2013_cerber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_2013_cerber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_202_demkni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_202_demkni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_204_platnm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_204_platnm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_208_melan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_208_melan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_210_stward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_210_stward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_211_adnach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_211_adnach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_212_ansel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_212_ansel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_213_mostma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_213_mostma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_214_kafka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_214_kafka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_215_mantic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_215_mantic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_218_cuttle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_218_cuttle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_219_meteo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_219_meteo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_222_bpipe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_222_bpipe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_225_haak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_225_haak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_226_hmau() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_226_hmau", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_235_jesica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_235_jesica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_236_rope() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_236_rope", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_237_gravel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_237_gravel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_240_wyvern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_240_wyvern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_241_panda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_241_panda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_242_otter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_242_otter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_243_waaifu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_243_waaifu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_248_mgllan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_248_mgllan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_250_phatom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_250_phatom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_253_greyy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_253_greyy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_254_vodfox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_254_vodfox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_258_podego() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_258_podego", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_261_sddrag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_261_sddrag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_263_skadi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_263_skadi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_264_f12yin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_264_f12yin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_271_spikes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_271_spikes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_272_strong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_272_strong", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_274_astesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_274_astesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_277_sqrrel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_277_sqrrel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_278_orchid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_278_orchid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_279_excu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_279_excu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_281_popka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_281_popka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_282_catap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_282_catap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_283_midn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_283_midn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_284_spot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_284_spot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_285_medic2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_285_medic2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_286_cast3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_286_cast3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_289_gyuki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_289_gyuki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_290_vigna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_290_vigna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_293_thorns() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_293_thorns", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_294_ayer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_294_ayer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_298_susuro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_298_susuro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_301_cutter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_301_cutter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_302_glaze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_302_glaze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_306_leizi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_306_leizi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_308_swire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_308_swire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_311_mudrok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_311_mudrok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_326_glacus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_326_glacus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_328_cammou() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_328_cammou", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_332_archet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_332_archet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_337_utage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_337_utage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_338_iris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_338_iris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_340_shwaz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_340_shwaz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_343_tknogi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_343_tknogi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_344_beewax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_344_beewax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_346_aosta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_346_aosta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_347_jaksel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_347_jaksel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_349_chiave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_349_chiave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_350_surtr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_350_surtr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_356_broca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_356_broca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_358_lisa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_358_lisa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_362_saga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_362_saga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_363_toddi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_363_toddi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_365_aprl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_365_aprl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_366_acdrop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_366_acdrop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_367_swllow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_367_swllow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_373_lionhd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_373_lionhd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_376_therex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_376_therex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_378_asbest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_378_asbest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_379_sesa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_379_sesa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_381_bubble() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_381_bubble", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_385_finlpp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_385_finlpp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_400_weedy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_400_weedy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_4000_jnight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_4000_jnight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_401_elysm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_401_elysm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_4093_frston() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_4093_frston", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_4136_phonor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_4136_phonor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_415_flint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_415_flint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_416_zumama() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_416_zumama", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_4188_confes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_4188_confes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_423_blemsh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_423_blemsh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_436_whispr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_436_whispr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_440_pinecn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_440_pinecn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_452_bstalk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_452_bstalk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_455_nothin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_455_nothin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_472_pasngr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_472_pasngr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_500_noirc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_500_noirc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_501_durin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_501_durin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_502_nblade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_502_nblade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property char_503_rang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_503_rang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property operators_with_ids() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("operators_with_ids", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Recruitment_Permit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Recruitment_Permit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Recruitment_Permit_Tiny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Recruitment_Permit_Tiny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tagtemplate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tagtemplate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
